version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - private_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    container_name: logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/config
    command: logstash -f /usr/share/logstash/config/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - private_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - private_network

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.15.0
    container_name: apm-server
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    env_file:
      - .env.elk-apm
    ports:
      - 8200:8200
    networks:
      - private_network
    depends_on:
      - elasticsearch

  emart-auth-rds:
    container_name: emart-auth-rds
    image: postgres:latest
    env_file:
      - auth/.env.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - private_network
    depends_on:
      - apm-server

  emart-auth-cache:
    container_name: emart-auth-cache
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
      - redisconfig:/etc/redis
    restart: on-failure
    networks:
      - private_network
    depends_on:
      - apm-server

  emart-auth-api:
    container_name: emart-auth-api
    build:
      context: ./auth
    working_dir: /auth
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - OAUTHLIB_INSECURE_TRANSPORT=1
    env_file:
      - auth/.env
    volumes:
      - ./auth:/auth
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - public_network
      - private_network
    depends_on:
      - emart-auth-rds
      - emart-auth-cache

volumes:
  pgdata:
  redisdata:
  redisconfig:
  elasticsearch_data:

networks:
  private_network:
  public_network:
