version: "3.9"

services:
  emart-auth-cache:
    container_name: emart-auth-cache
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
      - redisconfig:/etc/redis
    restart: on-failure
    networks:
      - private_network

  emart-auth-api:
    container_name: emart-auth-api
    build:
      context: ./auth
    working_dir: /auth
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - auth/.env
    volumes:
      - ./auth:/auth
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - public_network
      - private_network

volumes:
  pgdata:
  redisdata:
  redisconfig:

networks:
  private_network:
  public_network:
