version: "3.9"

services:
  auth_db:
    container_name: auth_db
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - private_network

  auth:
    container_name: emart-auth
    build: .
    working_dir: /server
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - public_network
    depends_on:
      - auth_db

volumes:
  pgdata:

networks:
  private_network:
  public_network:
