"""db_v2.

Revision ID: fce8d296d1fc
Revises: 51c15a1a7f5d
Create Date: 2024-01-28 16:17:30.144858
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fce8d296d1fc"  # pragma: allowlist secret
down_revision: Union[str, None] = "51c15a1a7f5d"  # pragma: allowlist secret
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=False),
        sa.Column("city", sa.String(length=256), nullable=False),
        sa.Column("address", sa.String(length=1024), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=False),
        sa.Column("links", sa.JSON(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["merchant_id"], ["account.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shop_city"), "shop", ["city"], unique=False)
    op.create_index(op.f("ix_shop_country"), "shop", ["country"], unique=False)
    op.create_index(op.f("ix_shop_is_verified"), "shop", ["is_verified"], unique=False)
    op.create_index(op.f("ix_shop_merchant_id"), "shop", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_shop_name"), "shop", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shop_name"), table_name="shop")
    op.drop_index(op.f("ix_shop_merchant_id"), table_name="shop")
    op.drop_index(op.f("ix_shop_is_verified"), table_name="shop")
    op.drop_index(op.f("ix_shop_country"), table_name="shop")
    op.drop_index(op.f("ix_shop_city"), table_name="shop")
    op.drop_table("shop")
    # ### end Alembic commands ###
