"""db_v3.

Revision ID: 4420f206c636
Revises: a876819efb5b
Create Date: 2023-09-16 07:20:51.164734
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4420f206c636"  # pragma: allowlist secret
down_revision: Union[str, None] = "a876819efb5b"  # pragma: allowlist secret
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profile", sa.Column("_birth_date", sa.Date(), nullable=True))
    op.add_column("profile", sa.Column("_gender", sa.String(length=1), nullable=True))
    op.drop_column("profile", "birth_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profile", sa.Column("birth_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column("profile", "_gender")
    op.drop_column("profile", "_birth_date")
    # ### end Alembic commands ###
