"""db_v7.

Revision ID: 50300b575595
Revises: a8dd6010a3c1
Create Date: 2023-10-11 17:54:45.287650
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50300b575595"  # pragma: allowlist secret
down_revision: Union[str, None] = "a8dd6010a3c1"  # pragma: allowlist secret
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_token",
        sa.Column("refresh_token", sa.String(length=1024), nullable=False),
        sa.Column("access_token", sa.String(length=1024), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("refresh_token"),
    )
    op.create_index(op.f("ix_refresh_token_access_token"), "refresh_token", ["access_token"], unique=True)
    op.create_index(op.f("ix_refresh_token_account_id"), "refresh_token", ["account_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_token_account_id"), table_name="refresh_token")
    op.drop_index(op.f("ix_refresh_token_access_token"), table_name="refresh_token")
    op.drop_table("refresh_token")
    # ### end Alembic commands ###
