"""db_v6.

Revision ID: a8dd6010a3c1
Revises: fa46cf0251ad
Create Date: 2023-10-01 16:15:02.152909
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8dd6010a3c1"  # pragma: allowlist secret
down_revision: Union[str, None] = "fa46cf0251ad"  # pragma: allowlist secret
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("open_id", sa.String(length=256), nullable=True))
    op.alter_column("account", "username", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.drop_constraint("account_email_key", "account", type_="unique")
    op.drop_constraint("account_username_key", "account", type_="unique")
    op.create_index(op.f("ix_account__provider"), "account", ["_provider"], unique=False)
    op.create_index(op.f("ix_account_email"), "account", ["email"], unique=True)
    op.create_index(op.f("ix_account_open_id"), "account", ["open_id"], unique=True)
    op.create_index(op.f("ix_account_username"), "account", ["username"], unique=True)
    op.create_index(op.f("ix_profile_account_id"), "profile", ["account_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profile_account_id"), table_name="profile")
    op.drop_index(op.f("ix_account_username"), table_name="account")
    op.drop_index(op.f("ix_account_open_id"), table_name="account")
    op.drop_index(op.f("ix_account_email"), table_name="account")
    op.drop_index(op.f("ix_account__provider"), table_name="account")
    op.create_unique_constraint("account_username_key", "account", ["username"])
    op.create_unique_constraint("account_email_key", "account", ["email"])
    op.alter_column("account", "username", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.drop_column("account", "open_id")
    # ### end Alembic commands ###
