"""db_v5.

Revision ID: fa46cf0251ad
Revises: bf32714a940c
Create Date: 2023-09-28 18:42:43.063150
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa46cf0251ad"  # pragma: allowlist secret
down_revision: Union[str, None] = "bf32714a940c"  # pragma: allowlist secret
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("account", "email", existing_type=sa.VARCHAR(length=256), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("account", "email", existing_type=sa.VARCHAR(length=256), nullable=False)
    # ### end Alembic commands ###
